/*
Velo Payments APIs

Testing FundingManagerPrivateAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package velopayments

import (
	"testing"
)

func Test_velopayments_FundingManagerPrivateAPIService(t *testing.T) {

	// configuration := NewConfiguration()
	// apiClient := NewAPIClient(configuration)

	t.Run("Test FundingManagerPrivateAPIService CreateFundingAccountV2", func(t *testing.T) {

		t.Skip("skip test")

	})

	t.Run("Test FundingManagerPrivateAPIService DeleteSourceAccountV3", func(t *testing.T) {

		t.Skip("skip test")

	})

}
